### ISSUE TITLE
Headline order

### ISSUE THREAD

**Issue by martinbethann** [stowball/react-accessible-tabs#3]
Hello,

I just wanted to mention that the use of H3s may potentially cause accessibility issues if the headine order conflicts with existing page structure.  Checkout https://www.w3.org/TR/wai-aria-practices/examples/tabs/tabs.html for an example.

Thanks!

**Comment by stowball** [comment]
Hi. Yep. The headings aren't part of the component, but the content/components you pass in (see https://github.com/stowball/react-accessible-tabs/blob/master/demo/src/index.js#L10)

**Comment by martinbethann** [comment]
Ahhh - sorry, my mistake - I was taking a looking in the wrong element.  Lovely - thank you for this!
