### ISSUE TITLE
ioS tabs and select boxes

### ISSUE THREAD

**Issue by martinbethann** [stowball/react-accessible-tabs#4]
Hello,

I just wanted to let you know that we are having an issue with ios and native select boxes.  There is something involving the tabs that is hijacking the native onchange event and preventing any selectbox from opening.

Thanks.

**Comment by martinbethann** [comment]
Removing: isSelected && this.refs[id] && this.refs[id].focus() from Tab.js allows the native selectbox to focus again.

**Comment by stowball** [comment]
Can you please post a reduced test case?

**Comment by Merri** [comment]
The current focus code is buggy and hijacks focus from anything else each time `componentDidUpdate` triggers on a selected tab. Say, focus is in a search field, a render happens as a result to typing something (search suggestions), `componentDidUpdate` is triggered and search field loses focus in the middle of writing.

`componentDidUpdate` is not an indicator of user action, and focus should only happen as a result of direct user action.

**Comment by stowball** [comment]
Thanks for this, @Merri. I'll look in to it
